### ISSUE TITLE
FileNotFoundException even the file does exist

### ISSUE THREAD

**Issue by nathanieltabanao** [cemdervis/SharpConfig#89]
I am trying to load a configuration file but it gives me an error even when the file does exist

`var config = Configuration.LoadFromFile (@"C:\\Users\IT\Desktop\user.cfg");`

I tried using a string variable but it still doesn't work

> System.IO.FileNotFoundException: 'Configuration file not found.'
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Configuration file not found.
  Source=SharpConfig
  StackTrace:
   at SharpConfig.Configuration.LoadFromFile(String filename, Encoding encoding)
   at SharpConfig.Configuration.LoadFromFile(String filename)
   at AttendanceApp.Login.<LoginClick>d__7.MoveNext() in C:\Users\IT\Desktop\AttendanceApp\AttendanceApp\Login.xaml.cs:line 86
```

**Comment by cemdervis** [comment]
Your path is invalid: @"C:\\Users\IT\Desktop\user.cfg"
Should be: @"C:\Users\IT\Desktop\user.cfg"
