### ISSUE TITLE
Breaking change: Setting with empty value fails to convert to string

### ISSUE THREAD

**Issue by dittodhole** [cemdervis/SharpConfig#99]
Giving following .ini-file and class:

```ini
[FOO]
SETTING=
```

```csharp
public class FOO
{
  public string SETTING { get; set; }
}
```

Reading the file, and mapping the `Section` object to an actual object with `.SetValuesTo(object)` now fails with the:

```
SharpConfig.SettingValueCastException: Failed to convert value '' to type System.String.
   at SharpConfig.Setting.CreateObjectFromString(String value, Type dstType, Boolean tryConvert)
   at SharpConfig.Setting.GetValue(Type type)
   at SharpConfig.Section.SetValuesTo(Object obj)
   at MY CODE ^^
```

**Comment by cemdervis** [comment]
Hi, I couldn't reproduce the exception; the object is constructed with SETTING's value being the empty string. Please verify in [Setting.cs](https://github.com/cemdervis/SharpConfig/blob/master/Src/Setting.cs#L504) whether obj is the empty string or null.

**Comment by dittodhole** [comment]
Hi, and thanks for the follow-up!

Mea culpa, I have a custom `string`-converter, which returns `null` rather than `string.Empty` which makes the [following comparison](https://github.com/cemdervis/SharpConfig/blob/master/Src/Setting.cs#L506) fail.

**Comment by cemdervis** [comment]
Sure thing. So reading from the title, you expect the string conversion to return a null-string? Just to be clear. At this moment, an empty setting value will let the converter return an empty string respectively, because the conversion is valid. Only invalid conversions should return null.

**Comment by dittodhole** [comment]
I am not sure, whether I should expect this OOTB - but this is, where custom converters kick in :)

Naming a method `TryXXX` should follow the [best practice](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance#try-parse-pattern): indicate the success via a `bool`-return type (and the actual result via an `out`-parameter) rather than a magic value!

**Comment by dittodhole** [comment]
I am not sure, whether I should expect this OOTB - but this is, where custom converters kick in :)

Naming a method `TryXXX` should follow the [best practice](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance#try-parse-pattern): indicate the success via a `bool`-return type (and the actual result via an `out`-parameter) rather than a magic value!

**Comment by cemdervis** [comment]
Yes, the naming is unfortunate. However, I won't drastically change the converter API until the next major release. So for the time being, we'd have to stick with the magic null values.

**Comment by dittodhole** [comment]
Fair enough. I then have to wait for the next major release.

Thanks for your input!

**Comment by cemdervis** [comment]
I see. So you're able to work around this issue for now?

**Comment by dittodhole** [comment]
Yep, sticking to 3.2.8 ;)

**Comment by cemdervis** [comment]
Noted. Thanks for reporting these issues by the way.
